### ISSUE TITLE
litee-calltree depends on litee-symboltree

### ISSUE THREAD

**Issue by JA-Bar** [ldelossa/litee-calltree.nvim#1]
Hey cool plugin!

There's a dependency issue with litee-symboltree because the file `lua/litee/calltree/marshal.lua` gets its config from `require('litee.symboltree.config')`, so if you don't have symboltree it will throw an error. I like the recent refactoring though!

**Comment by ldelossa** [comment]
Thanks for the report. There maybe a few copy pasta mistakes like this. I just pushed a commit from my iphone lol, lmk if it works.

**Comment by JA-Bar** [comment]
It no longer errors out, thanks!
