### ISSUE TITLE
Get error "must make call tree request to LSP" when doing :LTPopOutCalltree

### ISSUE THREAD

**Issue by muppi090909** [ldelossa/litee-calltree.nvim#11]
I have been trying to get the call tree for Rust particularly but I get that error (mentioned in title) so i tried to doing :LTPanel but that said
there must be a existing litee component. Can somebody help me with this

**Comment by ldelossa** [comment]
`litee-calltree` is wired into Neovim's lsp functions. Did you attempt to directy or indirectly create a call heirarchy request? `lua vim.lsp.buf.incoming_calls` or `lua vim.lsp.buf.outgoing_calls` will do it.

**Comment by muppi090909** [comment]
after trying ```lua vim.lsp.buf.incoming_calls``` I got expected = near <eof>

**Comment by ldelossa** [comment]
@muppi090909 you'll have to read a few tutorials or checkout ":h vim.lsp" in neovim to figure out how to use those functions correctly. Most bind the functions to keymappings. 

Here's a good starting point: https://github.com/neovim/nvim-lspconfig#suggested-configuration

**Comment by muppi090909** [comment]
Could you give me your config for this? Also does it integrate with [this](https://github.com/williamboman/nvim-lsp-installer)

**Comment by muppi090909** [comment]
I copied you dotfiles for litee and this so could you kindly tell me in which order i must use them. Thank you
