### ISSUE TITLE
Some questions.

### ISSUE THREAD

**Issue by ravenxrz** [ldelossa/litee-calltree.nvim#12]
Thank you for this amazing plugin. 

Here are some questions after I used it for a while.

**The first question is:**

After I jump to a function symbol, my cursor color is lost.

Before calltree:

![image](https://user-images.githubusercontent.com/44746032/161409327-453d4eeb-33c2-46d9-aecd-341b53f7a54e.png)

After jumping to another function using calltree, I lost my black cursor.

![image](https://user-images.githubusercontent.com/44746032/161409358-74d50714-0188-441a-af9b-82dbf82613f3.png)

Maybe it's a bug of the theme I am using, but I encountered this problem both on onedark theme and darkplus theme. 

**The second question is:**

The scenario is I opened the calltree poup window, then I used "ctrl + w + l/r" to jump to source code. But how can I jump back to calltree window agian? It seems like the calltree window was stuck here forever.

![image](https://user-images.githubusercontent.com/44746032/161409520-1b0a004c-361d-4827-89ca-4dbcba6f060e.png)

**Comment by ravenxrz** [comment]
Seems like the first question is caused by the FixCursorHold plugin. After I disabled that, everything works fine.

**Comment by ravenxrz** [comment]
Finally, I find the 'hide_cursor' option is useful. Set it to false solve the first problem.

**Comment by ldelossa** [comment]
Hey! 

hide_cursor option seems to be buggy. Ive been thinking of just removing it all together. 

As far as your second question, you can always jump back into the "calltree" window by using "LTPopOutCalltree" if the call tree is opened in a PopOut panel, or "LTOpenToCalltree" if its in the side panel

**Comment by ravenxrz** [comment]
> LTPopOutCalltree

Okk, I get it.
