### ISSUE TITLE
'litee.lsp.handlers' not found

### ISSUE THREAD

**Issue by ziontee113** [ldelossa/litee-calltree.nvim#13]
Hi, this is my first time intsalling litee and I can't get it to work.
I tried:
```
require("litee.lib").setup({})
require("litee.calltree").setup({})
require("litee.symboltree").setup({})

vim.lsp.handlers['callHierarchy/incomingCalls'] = vim.lsp.with(
            require('litee.lsp.handlers').ch_lsp_handler("from"), {}
)
vim.lsp.handlers['callHierarchy/outgoingCalls'] = vim.lsp.with(
            require('litee.lsp.handlers').ch_lsp_handler("to"), {}
)
```
But it results in `'litee.lsp.handlers' not found` error.
I can't get any Litee commands to work at all.

**Comment by ldelossa** [comment]
Check this out as an example. 
https://github.com/ldelossa/dotfiles/blob/master/config/nvim/lua/configs/litee.lua

you shouldn't  need to do anything more then calling setup()

**Comment by ziontee113** [comment]
Thank you for responding :)
So I did just call the setup functions. There is no error. But the only Panel that I can open is the File Tree panel.

When I use `:LTOpenToSymbolTree`, nothing happens, or there is a red popup that says: "You must perform a document symbol LSP request first"
When I use `:LTOpenToCallTree`, nothing happens, or there is a red popup that says kind of the same thing, about LSP related stuff.

There are so many functions that I don't know what to do and how to set them up.

**Comment by ldelossa** [comment]
The calltree is only opened when a native LSP "incoming calls" or "outgoing calls" method is invoked. Checkout https://neovim.io/doc/user/lsp.html for more info. 

Most individuals will map the LSP function calls to key bindings

**Comment by ziontee113** [comment]
Hi @ldelossa , I got the Symbol Tree opened! The problem is that I run into another error while trying to open folds in it.
![wezterm-gui_0s3aUjaVsQ](https://user-images.githubusercontent.com/102876811/164354118-76e294cc-6bb5-467a-9f03-f5e9439cf5a0.png)

![wezterm-gui_G1V5oTqeWF](https://user-images.githubusercontent.com/102876811/164354119-05f5d5ab-cc65-4cb5-933b-d7f2c26fdb77.png)

**Comment by ldelossa** [comment]
If you disable beacon plugin does it work?

**Comment by ziontee113** [comment]
Sorry. That's my bad! It works now :)
