### ISSUE TITLE
Outgoing Jump error

### ISSUE THREAD

**Issue by crusj** [ldelossa/litee-calltree.nvim#14]
```<CR>``` jump outgoint
E5108: Error executing lua ...lar/neovim/0.7.0/share/nvim/runtime/lua/vim/lsp/util.lua:1016: Vim(lua):E5108: Error executing lua ...tart/litee-calltree.nvim/lua/litee/calltree/handlers.
lua:344: end_row value outside range
stack traceback:
        [C]: in function 'nvim_buf_set_extmark'
        ...tart/litee-calltree.nvim/lua/litee/calltree/handlers.lua:344: in function '_update_calltree_extmarks'
        ...tart/litee-calltree.nvim/lua/litee/calltree/handlers.lua:412: in function 'update_calltree_extmarks'
        [string ":lua"]:1: in main chunk
        [C]: in function 'nvim_set_current_buf'
        ...lar/neovim/0.7.0/share/nvim/runtime/lua/vim/lsp/util.lua:1016: in function 'jump_to_location'
        ...ack/packer/start/litee.nvim/lua/litee/lib/jumps/init.lua:150: in function 'jump_invoking'
        ...er/start/litee-calltree.nvim/lua/litee/calltree/init.lua:297: in function 'jump_calltree'
        [string ":lua"]:1: in main chunk
stack traceback:
        [C]: in function 'nvim_set_current_buf'
        ...lar/neovim/0.7.0/share/nvim/runtime/lua/vim/lsp/util.lua:1016: in function 'jump_to_location'
        ...ack/packer/start/litee.nvim/lua/litee/lib/jumps/init.lua:150: in function 'jump_invoking'
        ...er/start/litee-calltree.nvim/lua/litee/calltree/init.lua:297: in function 'jump_calltree'
        [string ":lua"]:1: in main chunk
        

```<Ctrl-o> back```
Error detected while processing BufEnter Autocommands for "*":
E5108: Error executing lua ...tart/litee-calltree.nvim/lua/litee/calltree/handlers.lua:344: end_row value outside range
stack traceback:
        [C]: in function 'nvim_buf_set_extmark'
        ...tart/litee-calltree.nvim/lua/litee/calltree/handlers.lua:344: in function '_update_calltree_extmarks'
        ...tart/litee-calltree.nvim/lua/litee/calltree/handlers.lua:412: in function 'update_calltree_extmarks'
        [string ":lua"]:1: in main chunk
        
```LTClosePanelPopOut```
﻿E5108: Error executing lua ...er/start/litee-calltree.nvim/lua/litee/calltree/init.lua:118: Vim(lua):E5108: Error executing lua ...tart/litee-calltree.nvim/lua/litee/calltree/handlers.l
ua:344: col value outside range
stack traceback:
        [C]: in function 'nvim_buf_set_extmark'
        ...tart/litee-calltree.nvim/lua/litee/calltree/handlers.lua:344: in function '_update_calltree_extmarks'
        ...tart/litee-calltree.nvim/lua/litee/calltree/handlers.lua:412: in function 'update_calltree_extmarks'
        [string ":lua"]:1: in main chunk
        [C]: in function 'nvim_win_close'
        ...er/start/litee-calltree.nvim/lua/litee/calltree/init.lua:118: in function 'close_calltree'
        [string ":lua"]:1: in main chunk
stack traceback:
        [C]: in function 'nvim_win_close'
        ...er/start/litee-calltree.nvim/lua/litee/calltree/init.lua:118: in function 'close_calltree'
        [string ":lua"]:1: in main chunk
﻿﻿

**Comment by cormacrelf** [comment]
May have something to do with the file encoding not being taken into account. Nvim 0.9 tells me when using call tree.nvim, "jump_to_location must be called with valid offset encoding" and "show_document must be called with valid offset encoding".
