### ISSUE TITLE
Default keymap doesn't work.

### ISSUE THREAD

**Issue by rhcher** [ldelossa/litee-calltree.nvim#4]
I see the correct display with this plugin installed, but the default keymap don't work at all.

**Comment by ldelossa** [comment]
The keymap inside the buffer?

**Comment by rhcher** [comment]
Yes, if I understand correctly, litee should have automatically configured the keys in the relevant buf.

**Comment by ldelossa** [comment]
That is correct, does `zo` not expand a node for you? Haven't had a problem with the default mappings yet.

**Comment by rhcher** [comment]
yes, all keymap in the special buffer don't work at all, I will look into this issue.
